// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.assignment.Persistance;

#nullable disable

namespace com.assignment.Persistance.Migrations
{
    [DbContext(typeof(TariffCalculationDbContext))]
    [Migration("20230108153254_MappingTableInDatabase")]
    partial class MappingTableInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("com.assignment.DomainEntities.TariffDetails", b =>
                {
                    b.Property<int>("TariffId")
                        .HasColumnType("int")
                        .HasColumnName("tariff_id");

                    b.Property<int>("EndUnit")
                        .HasColumnType("int")
                        .HasColumnName("end_unit");

                    b.Property<long>("EnergyRate")
                        .HasColumnType("bigint")
                        .HasColumnName("energy_rate");

                    b.Property<long>("ServiceCharge")
                        .HasColumnType("bigint")
                        .HasColumnName("service_charge");

                    b.Property<int>("StartUnit")
                        .HasColumnType("int")
                        .HasColumnName("start_unit");

                    b.HasKey("TariffId")
                        .HasName("pk_tariff_details");

                    b.ToTable("tariff_details", (string)null);
                });

            modelBuilder.Entity("com.assignment.DomainEntities.TariffMaster", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tariff_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<int>("PenaltyDays")
                        .HasColumnType("int")
                        .HasColumnName("penalty_days");

                    b.Property<long>("PenaltyRate")
                        .HasColumnType("bigint")
                        .HasColumnName("penalty_rate");

                    b.Property<int>("RebateDays")
                        .HasColumnType("int")
                        .HasColumnName("rebate_days");

                    b.Property<long>("RebateRate")
                        .HasColumnType("bigint")
                        .HasColumnName("rebate_rate");

                    b.HasKey("TariffId")
                        .HasName("pk_tariff_master");

                    b.ToTable("tariff_master", (string)null);
                });

            modelBuilder.Entity("com.assignment.DomainEntities.TariffDetails", b =>
                {
                    b.HasOne("com.assignment.DomainEntities.TariffMaster", "TarifMaster")
                        .WithMany("TariffDetails")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_details_tariff_masters_tarif_master_temp_id");

                    b.Navigation("TarifMaster");
                });

            modelBuilder.Entity("com.assignment.DomainEntities.TariffMaster", b =>
                {
                    b.Navigation("TariffDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
